### ISSUE TITLE
Code has a few bugs

### ISSUE THREAD

**Issue by ShaofengZou** [mit-han-lab/deep-leakage-from-gradients#2]
Hey,  l find that this study is very interesting and helpful.

So I am trying to run your code but find some bugs.

**In main.py:**
* Line 48,

   > from model.vision import LeNet

   Should be:

   > from models.vision import LeNet

* Line 51,

    > net.apply(weights_init)

    the name 'weights_init' is not defined.

Looking forward to your reply.

**Comment by Lyken17** [comment]
Thanks for pointing out. Fixed.
