### ISSUE TITLE
I can not recover the image from the gradients.

### ISSUE THREAD

**Issue by 6lyc** [mit-han-lab/deep-leakage-from-gradients#9]
Why can't I reproduce the effect of the paper? According to your code, the image I get is just some disordered pixel blocks, even if I increase the number of iterations.

**Comment by 6lyc** [comment]
It should set a little learning rate, otherwise the dlg model will not converge.

**Comment by FryLcm** [comment]
> 应该设置一点学习率，否则dlg模型不会收敛。

能详细说下怎么解决吗

**Comment by 6lyc** [comment]
See https://github.com/6lyc/DLG-and-its-defense.git for more details. @FryLcm

**Comment by FryLcm** [comment]
> 有关更多详细信息，请参阅[https://github.com/6lyc/DLG-and-its-defense.git 。](https://github.com/6lyc/DLG-and-its-defense.git)@FryLcm

感谢您的回复！
